name: Build (Windows MSVC)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: trifecta-driver-windows-msvc-ci-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-msvc:
    runs-on: [self-hosted, Windows, MSVC]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true 

      - name: Build project with MSVC
        run: |
          ./build_windows_msvc.bat "$BUILD_KIND"

